server:
  port: 8888

spring:
  application:
    name: @build.finalName@
#
eureka:
  client:
    #false表示不向注册中心注册自己。
#    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka01.ms.svc.cluster.local:${server.port}/eureka/,http://eureka02.ms.svc.cluster.local:${server.port}/eureka/

# 定义日志级别  debug , info
logback:
#  使用 pom当中的参数
  name: @build.finalName@
  path: /home/cloud/@build.finalName@/
  level: info

# 配置日志
logging:
  config: classpath:logback-eureka.xml