server:
  port: 8060


thierrysquirrel:
  access-key: aaa
  name-srv-addr: aaa
  secret-key: aaa



spring:
  application:
    # 应用程序名称，后面会在消费者中用到
    name: @build.finalName@
# 定义日志级别  debug , info
logback:
#  使用 pom当中的参数
  name: ${spring.application.name}
  path: /home/cloud/${logback.name}/
  level: info

# 配置日志
logging:
  config: classpath:logback-mq.xml