server:
  port: 8060


thierrysquirrel:
  access-key: LTAIv5qnbcZaPFXc
  name-srv-addr: http://MQ_INST_1915403512691337_BbNxQksA.mq-internet-access.mq-internet.aliyuncs.com:80
  secret-key: puCIqpmHXijZ29WTWoCSAcPjHlzgHD



spring:
  application:
    # 应用程序名称，后面会在消费者中用到
    name: @build.finalName@
# 定义日志级别  debug , info
logback:
#  使用 pom当中的参数
  name: ${spring.application.name}
  path: /home/cloud/${logback.name}/
  level: info

# 配置日志
logging:
  config: classpath:logback-mq.xml